<?php
$_orderId = $this->getMethod()->getInfoInstance()->getParentId();
$_paymentInfo = $this->getPaymentInfo($_orderId);
$_description = $this->getPaymentDescription($_orderId);

echo '<strong>' . $this->getMethod()->getTitle() . '</strong><br/>';

echo '<em>' . $this->__($_description) . '</em><br />';

echo $this->__('Reference Id: %s', $this->htmlEscape($_paymentInfo->getTransactionReferenceId())) . '<br />';
